Repository f-o-a-m/kepler, pull requests merged in 2020-01, with the labels that each got.

#193 Docs polish
  README.md
  hs-abci-examples/nameservice/README.md
  hs-abci-examples/nameservice/docs/Logging.md
  hs-abci-examples/nameservice/docs/Metrics.md
Labels: documentation

#195 WIP: Plain travis
  .travis.yml
Labels: WIP

#199 Generalized router
  hs-abci-sdk/package.yaml
  hs-abci-sdk/src/Tendermint/SDK/BaseApp/Query.hs
  hs-abci-sdk/src/Tendermint/SDK/BaseApp/Query/Class.hs
  hs-abci-sdk/src/Tendermint/SDK/BaseApp/Query/Delayed.hs
  hs-abci-sdk/src/Tendermint/SDK/BaseApp/Query/Router.hs
  hs-abci-sdk/src/Tendermint/SDK/BaseApp/Query/Store.hs
  hs-abci-sdk/src/Tendermint/SDK/BaseApp/Query/Types.hs
  hs-abci-sdk/src/Tendermint/SDK/BaseApp/Router.hs
  hs-abci-sdk/src/Tendermint/SDK/BaseApp/Router/Delayed.hs
  hs-abci-sdk/src/Tendermint/SDK/BaseApp/Router/Router.hs
  hs-abci-sdk/src/Tendermint/SDK/BaseApp/Router/Types.hs
Labels: refactor, sdk
